AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  owno-backend
  Sample SAM Template for owno-backend

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  # API Gateway Definition
  OwnoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE

  # Lambda Function
  OwnoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: owno/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        Owno:
          Type: Api
          Properties:
            Path: /register
            Method: POST
            RestApiId: !Ref OwnoApi

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  OwnoApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${OwnoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register"
  OwnoFunction:
    Description: Lambda Function ARN
    Value: !GetAtt OwnoFunction.Arn
  OwnoFunctionIamRole:
    Description: Implicit IAM Role created for function
    Value: !GetAtt OwnoFunctionRole.Arn